//	Header generated by Constructor for Palm OS¨ 1.5
//
//	Generated at 12:55:20 AM on 2003¦~6¤ë7¤é
//
//	Generated for file: D:\PDA\PDA programming\MbcWJFX\VPL2\Src\starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"MbcWJFX"
//
//	Palm App Version: 		"0.1"



//	Resource: tFRM 1000
#define BlockDiagramForm                          1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)


//	Resource: tFRM 1100
#define FrontPanelForm                            1100	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)


//	Resource: tFRM 1200
#define AboutForm                                 1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutUnnamed1201BitMap                    1000	//(Left Origin = 38, Top Origin = 30, Bitmap Resource ID = 1000, Usable = 1)
#define AboutUnnamed1206BitMap                    1900	//(Left Origin = 71, Top Origin = 121, Bitmap Resource ID = 1900, Usable = 1)
#define AboutUnnamed1202Label                     1202	//(Left Origin = 62, Top Origin = 30, Usable = 1, Font = Bold 12)
#define AboutUnnamed1203Label                     1203	//(Left Origin = 40, Top Origin = 65, Usable = 1, Font = Standard)
#define AboutUnnamed1204Label                     1204	//(Left Origin = 38, Top Origin = 110, Usable = 1, Font = Bold)


//	Resource: tFRM 1300
#define FunctionsForm                             1300	//(Left Origin = 50, Top Origin = 1, Width = 100, Height = 157, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: tFRM 1400
#define LOADForm                                  1400	//(Left Origin = 1, Top Origin = 22, Width = 158, Height = 136, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define LOADLOADButton                            1402	//(Left Origin = 119, Top Origin = 120, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define LOADDELETEButton                          1403	//(Left Origin = 74, Top Origin = 120, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define LOADCANCELButton                          1404	//(Left Origin = 29, Top Origin = 120, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define LOADFileListList                          1401	//(Left Origin = 2, Top Origin = 14, Width = 154, Usable = 1, Font = Standard, Visible Items = 9)


//	Resource: tFRM 1500
#define UIsForm                                   1500	//(Left Origin = 118, Top Origin = 1, Width = 40, Height = 80, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: tFRM 1600
#define SAVEForm                                  1600	//(Left Origin = 1, Top Origin = 94, Width = 158, Height = 64, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SAVEOKButton                              1602	//(Left Origin = 114, Top Origin = 47, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SAVECANCELButton                          1603	//(Left Origin = 65, Top Origin = 47, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Bold)
#define SAVEFileNameField                         1601	//(Left Origin = 8, Top Origin = 24, Width = 144, Height = 16, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 32, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)


//	Resource: tFRM 1700
#define EditIconForm                              1700	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: tFRM 1800
#define BlockToolsForm                            1800	//(Left Origin = 118, Top Origin = 1, Width = 40, Height = 109, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: tFRM 1900
#define PanelToolsForm                            1900	//(Left Origin = 118, Top Origin = 1, Width = 40, Height = 80, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define DeleteFileComfirAlert                     1000
#define DeleteFileComfirOK                        0
#define DeleteFileComfirCANCEL                    1

//	Resource: Talt 1100
#define MESSAGEAlert                              1100
#define MESSAGEOK                                 0

//	Resource: MBAR 1000
#define BlockDiagramMenuBar                       1000

//	Resource: MBAR 1100
#define FrontPanelMenuBar                         1100

//	Resource: MENU 1000
#define AboutMenu                                 1000
#define AboutAboutMbcWJFX                         1000

//	Resource: MENU 1100
#define FileMenu                                  1100
#define FileNEW                                   1100
#define FileSAVE                                  1101
#define FileLOAD                                  1102

//	Resource: MENU 1200
#define BlockDiagramWorksMenu                     1200
#define BlockDiagramWorksBlockDiagram             1200
#define BlockDiagramWorksFrontPanel               1201
#define BlockDiagramWorksFunctions                1203

//	Resource: MENU 1300
#define RunMenu                                   1300
#define RunRun                                    1300
#define RunStop                                   1301

//	Resource: MENU 1400
#define UntitledMenu                              1400

//	Resource: MENU 1500
#define FrontPanelWorksMenu                       1500
#define FrontPanelWorksBlockDiagram               1500
#define FrontPanelWorksFrontPanel                 1501
#define FrontPanelWorksUIs                        1503

//	Resource: PICT 1800
#define UISBitmap                                 1800
//	Resource: PICT 1700
#define CONSTU8Bitmap                             1700
//	Resource: PICT 1600
#define TOOLSBitmap                               1600
//	Resource: PICT 1500
#define CTRLU8Bitmap                              1500
//	Resource: PICT 1400
#define INDICATOR8Bitmap                          1400
//	Resource: PICT 1000
#define ADDBitmap                                 1000
//	Resource: PICT 1100
#define SUBBitmap                                 1100
//	Resource: PICT 1200
#define MULBitmap                                 1200
//	Resource: PICT 1300
#define DIVBitmap                                 1300
//	Resource: PICT 1900
#define dahaiBitmap                               1900
//	Resource: PICT 2000
#define CLENCHBitmap                              2000
//	Resource: PICT 2100
#define HANDBitmap                                2100
//	Resource: PICT 2200
#define BLANKBitmap                               2200
//	Resource: PICT 2300
#define RUNBitmap                                 2300
//	Resource: PICT 2400
#define PAUSEBitmap                               2400
//	Resource: PICT 2500
#define STOPBitmap                                2500
//	Resource: PICT 2600
#define LAMPBitmap                                2600
//	Resource: PICT 2700
#define THREADBitmap                              2700
//	Resource: PICT 2800
#define FUNCTIONSBitmap                           2800
//	Resource: PICT 2900
#define ARROWBitmap                               2900
//	Resource: PICT 3000
#define FINGERBitmap                              3000
//	Resource: PICT 3100
#define INDICATOR8BLOCKBitmap                     3100
//	Resource: PICT 3200
#define CTRLU8BLOCKBitmap                         3200
//	Resource: PICT 3300
#define PRESSFINGERBitmap                         3300
//	Resource: PICT 3400
#define SCISSORBitmap                             3400
//	Resource: PICT 3500
#define KILLBitmap                                3500
//	Resource: PICT 3600
#define RUNMANBitmap                              3600
//	Resource: PICT 3700
#define STOPMANBitmap                             3700
//	Resource: PICT 3800
#define CUSTOMBLOCKBitmap                         3800
//	Resource: PICT 3900
#define ANDBitmap                                 3900
//	Resource: PICT 4000
#define ORBitmap                                  4000
//	Resource: PICT 4100
#define NOTBitmap                                 4100
//	Resource: PICT 4200
#define DRAGBitmap                                4200
//	Resource: PICT 4300
#define LEDONBitmap                               4300
//	Resource: PICT 4400
#define LEDOFFBitmap                              4400
//	Resource: PICT 4500
#define SWONBitmap                                4500
//	Resource: PICT 4600
#define SWOFFBitmap                               4600
//	Resource: PICT 4700
#define LOGICCTRLBitmap                           4700
//	Resource: PICT 4800
#define LOGICINDICATORBitmap                      4800
//	Resource: PICT 4900
#define FORLOOPBitmap                             4900
//	Resource: PICT 5000
#define WHILELOOPBitmap                           5000
//	Resource: PICT 5100
#define SWITCHCASEBitmap                          5100
//	Resource: PICT 5200
#define WHILELOOPLOOPBitmap                       5200
//	Resource: PICT 5300
#define LOOP1Bitmap                               5300
//	Resource: PICT 5400
#define LOOP2Bitmap                               5400
//	Resource: PICT 5500
#define LOOP3Bitmap                               5500
//	Resource: PICT 5600
#define LOOP4Bitmap                               5600
//	Resource: PICT 5700
#define LOOP5Bitmap                               5700
//	Resource: PICT 5800
#define SC1Bitmap                                 5800
//	Resource: PICT 5900
#define SC2Bitmap                                 5900
//	Resource: PICT 6000
#define untitledBitmap                            6000
//	Resource: PICT 6100
#define FUNCARITHBitmap                           6100
//	Resource: PICT 6200
#define FUNCLOGICBitmap                           6200
//	Resource: PICT 6300
#define FUNCSTRUCTBitmap                          6300
//	Resource: PICT 6400
#define FUNCSTRBitmap                             6400
//	Resource: PICT 6500
#define FUNCCUSTBitmap                            6500
//	Resource: PICT 6600
#define FUNCARRAYBitmap                           6600
//	Resource: PICT 6700
#define FUNCTIMEBitmap                            6700
//	Resource: PICT 6800
#define FUNCCOMPBitmap                            6800
//	Resource: PICT 6900
#define FUNCFILEBitmap                            6900
//	Resource: PICT 7000
#define ABOVEBitmap                               7000
//	Resource: PICT 7100
#define LESSBitmap                                7100
//	Resource: PICT 7200
#define EQUBitmap                                 7200
//	Resource: PICT 7300
#define ABOVEEQUBitmap                            7300
//	Resource: PICT 7400
#define LESSEQUBitmap                             7400
//	Resource: PICT 7500
#define STOPUNUSEBitmap                           7500
//	Resource: PICT 7600
#define LAMPLIGHTBitmap                           7600
//	Resource: PICT 7700
#define STOPWAITBitmap                            7700
//	Resource: PICT 7800
#define RUNWAITBitmap                             7800
//	Resource: PICT 7900
#define FORLOOPNBitmap                            7900
//	Resource: PICT 8000
#define FORLOOPIBitmap                            8000
//	Resource: PICT 8100
#define PENCILBitmap                              8100
//	Resource: PICT 8200
#define RUNRUNWAITBitmap                          8200
//	Resource: PICT 8300
#define RUNRUNBitmap                              8300